CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(140) NOT NULL,
  slug VARCHAR(170) NOT NULL UNIQUE,
  icon_class VARCHAR(80) NULL,
  description TEXT NULL,
  job_count INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_categories_status (status),
  INDEX idx_categories_sort_order (sort_order)
);

CREATE TABLE IF NOT EXISTS jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  company_id INT NULL,
  company_name VARCHAR(180) NOT NULL,
  category VARCHAR(140) NOT NULL,
  category_id INT NULL,
  location VARCHAR(180) NOT NULL,
  job_type VARCHAR(80) NOT NULL DEFAULT 'Full-time',
  salary VARCHAR(120) NULL,
  experience VARCHAR(80) NULL,
  gender VARCHAR(80) NULL,
  qualification VARCHAR(140) NULL,
  level VARCHAR(80) NULL,
  vacancy VARCHAR(80) NULL,
  description TEXT NULL,
  responsibilities TEXT NULL,
  requirements TEXT NULL,
  education_requirements TEXT NULL,
  working_hours TEXT NULL,
  benefits TEXT NULL,
  statement TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  deadline DATE NULL,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_jobs_category (category),
  INDEX idx_jobs_category_id (category_id),
  INDEX idx_jobs_status (status),
  INDEX idx_jobs_location (location)
);

INSERT INTO categories (name, slug, icon_class, description, job_count, sort_order, status)
VALUES
  ('Accounting/Finance', 'accounting-finance', 'icofont-money', 'Finance, accounting, payroll, and audit career openings.', 305, 1, 'active'),
  ('Production/Operation', 'production-operation', 'icofont-industries', 'Operations, logistics, manufacturing, and production roles.', 95, 2, 'active'),
  ('Education/Training', 'education-training', 'icofont-graduate', 'Teaching, training, curriculum, and learning support jobs.', 212, 3, 'active'),
  ('Design/Creative', 'design-creative', 'icofont-paint', 'Creative design, brand, product, UI, and visual roles.', 93, 4, 'active'),
  ('Health & Fitness', 'health-fitness', 'icofont-heart-beat', 'Health, wellness, fitness, and care-focused opportunities.', 4, 5, 'active'),
  ('Research/Consultancy', 'research-consultancy', 'icofont-search-job', 'Research, consulting, analysis, and advisory positions.', 34, 6, 'active'),
  ('Engineer/Architects', 'engineer-architects', 'icofont-engineer', 'Engineering, architecture, construction, and technical design jobs.', 376, 7, 'active'),
  ('Telecommunication', 'telecommunication', 'icofont-signal', 'Network, telecom, wireless, and connectivity roles.', 450, 8, 'active'),
  ('Data Entry/Operator', 'data-entry-operator', 'icofont-keyboard', 'Data entry, operations support, and back-office roles.', 25, 9, 'active'),
  ('Marketing/Sales', 'marketing-sales', 'icofont-chart-growth', 'Sales, marketing, growth, partnerships, and account jobs.', 666, 10, 'active'),
  ('Security/Support Service', 'security-support-service', 'icofont-shield', 'Security, customer support, and service operations roles.', 62, 11, 'active')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  icon_class = VALUES(icon_class),
  description = VALUES(description),
  job_count = VALUES(job_count),
  sort_order = VALUES(sort_order),
  status = VALUES(status);

INSERT INTO jobs (
  title,
  slug,
  company_name,
  category,
  location,
  job_type,
  salary,
  experience,
  gender,
  qualification,
  level,
  vacancy,
  description,
  responsibilities,
  requirements,
  education_requirements,
  working_hours,
  benefits,
  statement,
  status,
  deadline,
  expires_at
)
VALUES
  (
    'Senior Web Developer',
    'senior-web-developer-obelus',
    'Obelus Concepts Ltd.',
    'Engineer/Architects',
    'New York, USA',
    'Full-time',
    '$5,000 / Monthly',
    '5 Years',
    'Male or Female',
    'BSC, MSC',
    'Senior',
    '3',
    'Build and maintain customer-facing web products for a growing digital services team. The role covers frontend delivery, backend integration, performance, and production support.',
    'Develop responsive web applications, Create reusable UI components, Integrate REST APIs, Improve page speed and accessibility, Collaborate with design and product teams.',
    'Strong JavaScript, HTML, CSS, and API integration experience, Practical knowledge of React or similar UI libraries, Ability to debug production issues, Comfortable working with Git workflows.',
    'Bachelor degree or equivalent practical software engineering experience.',
    '8:00 AM - 5:00 PM, Weekly: 5 days, Weekend: Saturday, Sunday.',
    'Medical cover, Performance bonus, Paid training, Annual team retreat, Flexible work support.',
    'Career Recruit is committed to equal opportunity for all qualified applicants.',
    'active',
    '2026-11-20',
    '2026-11-20 23:59:59'
  ),
  (
    'Financial Operations Analyst',
    'financial-operations-analyst-clearledger',
    'ClearLedger Group',
    'Accounting/Finance',
    'Austin, USA',
    'Full-time',
    '$4,200 / Monthly',
    '3 Years',
    'Male or Female',
    'BSC Accounting or Finance',
    'Mid',
    '2',
    'Support monthly reporting, account reconciliation, payment tracking, and finance operations across client accounts.',
    'Prepare finance reports, Reconcile accounts, Track payment exceptions, Support audit requests, Improve reporting templates.',
    'Accounting or finance operations experience, Spreadsheet fluency, Strong attention to detail, Clear written communication.',
    'Degree in accounting, finance, economics, or equivalent work experience.',
    '9:00 AM - 5:00 PM, Weekly: 5 days.',
    'Health insurance, Paid certification support, Hybrid work days, Annual bonus plan.',
    'Career Recruit supports fair hiring and inclusive finance teams.',
    'active',
    '2026-10-15',
    '2026-10-15 23:59:59'
  ),
  (
    'Digital Marketing Manager',
    'digital-marketing-manager-greenline',
    'Greenline Commerce',
    'Marketing/Sales',
    'Remote',
    'Full-time',
    '$4,800 / Monthly',
    '4 Years',
    'Male or Female',
    'BSC, BA, or equivalent',
    'Senior',
    '1',
    'Lead paid acquisition, lifecycle campaigns, content planning, and conversion reporting for a fast-growing ecommerce brand.',
    'Own campaign calendars, Manage paid search and social channels, Report CAC and ROAS, Coordinate landing pages, Test messaging.',
    'Hands-on digital marketing experience, Strong analytics skills, Familiarity with paid media tools, Ability to manage budgets.',
    'Marketing, communications, business, or equivalent practical experience.',
    'Flexible remote schedule, Weekly: 5 days.',
    'Remote work stipend, Performance bonus, Learning budget, Wellness allowance.',
    'Career Recruit welcomes applicants from every background.',
    'active',
    '2026-09-30',
    '2026-09-30 23:59:59'
  ),
  (
    'UI Product Designer',
    'ui-product-designer-brightpath',
    'BrightPath Labs',
    'Design/Creative',
    'San Francisco, USA',
    'Contract',
    '$70 / Hourly',
    '4 Years',
    'Male or Female',
    'Portfolio Required',
    'Mid',
    '2',
    'Design polished web and mobile product experiences, from discovery sketches through production-ready interface specs.',
    'Create user flows, Produce wireframes and high-fidelity screens, Maintain design systems, Review implementation quality, Run usability checks.',
    'Strong product design portfolio, Figma fluency, Understanding of responsive UI, Ability to communicate design tradeoffs.',
    'Design degree preferred, but portfolio strength is the primary requirement.',
    'Flexible hours, Weekly: 4-5 days.',
    'Remote flexibility, Design tools allowance, Paid workshops, Project completion bonus.',
    'Career Recruit encourages thoughtful, accessible product design.',
    'active',
    '2026-12-05',
    '2026-12-05 23:59:59'
  ),
  (
    'Network Support Engineer',
    'network-support-engineer-telcohub',
    'TelcoHub Systems',
    'Telecommunication',
    'Dallas, USA',
    'Full-time',
    '$4,600 / Monthly',
    '3 Years',
    'Male or Female',
    'BSC, HND, or technical certification',
    'Mid',
    '4',
    'Monitor network health, respond to incidents, and support enterprise connectivity services for telecom customers.',
    'Troubleshoot network incidents, Maintain ticket updates, Coordinate field teams, Document recurring issues, Support maintenance windows.',
    'Networking fundamentals, Experience with routers and switches, Incident response discipline, Clear customer communication.',
    'Network certification or equivalent hands-on infrastructure experience.',
    'Rotating shifts, Weekly: 5 days.',
    'Shift allowance, Certification support, Medical benefits, Paid leave.',
    'Career Recruit supports reliable service teams through fair hiring.',
    'active',
    '2026-10-28',
    '2026-10-28 23:59:59'
  )
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  company_name = VALUES(company_name),
  category = VALUES(category),
  location = VALUES(location),
  job_type = VALUES(job_type),
  salary = VALUES(salary),
  experience = VALUES(experience),
  gender = VALUES(gender),
  qualification = VALUES(qualification),
  level = VALUES(level),
  vacancy = VALUES(vacancy),
  description = VALUES(description),
  responsibilities = VALUES(responsibilities),
  requirements = VALUES(requirements),
  education_requirements = VALUES(education_requirements),
  working_hours = VALUES(working_hours),
  benefits = VALUES(benefits),
  statement = VALUES(statement),
  status = VALUES(status),
  deadline = VALUES(deadline),
  expires_at = VALUES(expires_at);
