INSERT INTO jobs (
  title,
  slug,
  company_name,
  category,
  location,
  job_type,
  salary,
  experience,
  gender,
  qualification,
  level,
  vacancy,
  description,
  responsibilities,
  requirements,
  education_requirements,
  working_hours,
  benefits,
  statement,
  status,
  deadline,
  expires_at
)
VALUES
  (
    'Remote Growth Marketing Specialist',
    'remote-growth-marketing-specialist-northstar',
    'Northstar Talent',
    'Marketing/Sales',
    'Remote',
    'Full-time',
    '$3,900 / Monthly',
    '3 Years',
    'Male or Female',
    'BA, BSC, or equivalent',
    'Mid',
    '3',
    'Plan and run acquisition campaigns for remote hiring products across paid search, social, and lifecycle channels.',
    'Build campaign briefs, Manage ad channel setup, Track leads and conversion quality, Report weekly growth metrics, Coordinate landing page updates.',
    'Performance marketing experience, Strong campaign reporting skills, Good writing ability, Comfortable with remote team workflows.',
    'Marketing, business, communications, or equivalent practical experience.',
    'Remote schedule, Weekly: 5 days.',
    'Remote stipend, Performance bonus, Learning budget, Paid leave.',
    'Career Recruit supports fair hiring for distributed teams.',
    'active',
    '2026-10-12',
    '2026-10-12 23:59:59'
  ),
  (
    'Remote Sales Development Representative',
    'remote-sales-development-representative-pipelineworks',
    'PipelineWorks',
    'Marketing/Sales',
    'Remote',
    'Full-time',
    '$3,200 / Monthly plus commission',
    '2 Years',
    'Male or Female',
    'Diploma or degree preferred',
    'Entry',
    '6',
    'Qualify inbound leads, book discovery calls, and support the sales pipeline for a B2B recruitment software team.',
    'Contact new leads, Book qualified meetings, Keep CRM records clean, Follow up on campaign responses, Share market feedback.',
    'Sales or customer-facing experience, Clear spoken English, CRM familiarity, Resilient follow-up habits.',
    'Formal degree is helpful but sales performance matters most.',
    'Remote shifts, Weekly: 5 days.',
    'Commission plan, Home office support, Sales coaching, Paid leave.',
    'Career Recruit welcomes applicants from every background.',
    'active',
    '2026-09-22',
    '2026-09-22 23:59:59'
  ),
  (
    'Remote Content Marketing Lead',
    'remote-content-marketing-lead-storylane',
    'Storylane Media',
    'Marketing/Sales',
    'Remote',
    'Full-time',
    '$4,700 / Monthly',
    '5 Years',
    'Male or Female',
    'BA, BSC, or portfolio',
    'Senior',
    '1',
    'Own content strategy for employer branding campaigns, candidate guides, and product-led growth materials.',
    'Plan editorial calendars, Write campaign copy, Manage freelancers, Review analytics, Improve lead magnets.',
    'Content strategy experience, Excellent writing samples, SEO fundamentals, Ability to manage deadlines.',
    'Communications, marketing, journalism, or equivalent portfolio experience.',
    'Flexible remote schedule, Weekly: 5 days.',
    'Remote work allowance, Healthcare support, Annual bonus, Training budget.',
    'Career Recruit values clear, useful communication.',
    'active',
    '2026-11-08',
    '2026-11-08 23:59:59'
  ),
  (
    'Remote Account Executive',
    'remote-account-executive-hiregrid',
    'HireGrid',
    'Marketing/Sales',
    'Remote',
    'Full-time',
    '$5,500 / Monthly plus commission',
    '4 Years',
    'Male or Female',
    'BSC or equivalent experience',
    'Senior',
    '2',
    'Close mid-market employer accounts and manage consultative sales cycles for online recruitment solutions.',
    'Run product demos, Negotiate proposals, Maintain sales forecast, Partner with customer success, Expand existing accounts.',
    'B2B sales experience, Strong demo skills, Pipeline ownership, Experience selling SaaS or recruitment services.',
    'Degree preferred, equivalent sales experience accepted.',
    'Remote schedule, Weekly: 5 days.',
    'Commission, Remote tools allowance, Paid leave, Growth coaching.',
    'Career Recruit supports transparent sales hiring.',
    'active',
    '2026-12-18',
    '2026-12-18 23:59:59'
  ),
  (
    'Remote Social Media Coordinator',
    'remote-social-media-coordinator-brandnest',
    'BrandNest Studio',
    'Marketing/Sales',
    'Remote',
    'Part-time',
    '$1,800 / Monthly',
    '2 Years',
    'Male or Female',
    'Portfolio preferred',
    'Entry',
    '2',
    'Coordinate social posts, community replies, and basic campaign reports for employer brand clients.',
    'Schedule posts, Write short captions, Monitor comments, Prepare weekly reports, Collect creative assets.',
    'Social media management experience, Good grammar, Basic analytics skills, Organized file handling.',
    'Portfolio or practical brand account experience preferred.',
    'Remote part-time schedule, Weekly: 4 days.',
    'Flexible hours, Content tools access, Paid training.',
    'Career Recruit encourages responsible online community work.',
    'active',
    '2026-08-29',
    '2026-08-29 23:59:59'
  ),
  (
    'Remote Network Operations Analyst',
    'remote-network-operations-analyst-netpulse',
    'NetPulse Systems',
    'Telecommunication',
    'Remote',
    'Full-time',
    '$4,300 / Monthly',
    '3 Years',
    'Male or Female',
    'BSC, HND, or certification',
    'Mid',
    '4',
    'Monitor telecom dashboards, triage incidents, and coordinate remote network support for enterprise customers.',
    'Watch alert queues, Escalate service incidents, Update tickets, Coordinate maintenance windows, Prepare incident summaries.',
    'Network operations experience, Ticketing discipline, Router and switch fundamentals, Clear incident communication.',
    'Networking certification or equivalent support experience.',
    'Remote shift schedule, Weekly: 5 days.',
    'Shift allowance, Certification support, Health benefits, Paid leave.',
    'Career Recruit supports reliable service operations.',
    'active',
    '2026-10-02',
    '2026-10-02 23:59:59'
  ),
  (
    'Remote VoIP Support Engineer',
    'remote-voip-support-engineer-callbridge',
    'CallBridge Telecom',
    'Telecommunication',
    'Remote',
    'Full-time',
    '$4,100 / Monthly',
    '3 Years',
    'Male or Female',
    'Technical certification preferred',
    'Mid',
    '3',
    'Support VoIP customers by troubleshooting call quality, SIP routing, and platform configuration issues.',
    'Troubleshoot call failures, Review logs, Configure routing updates, Document fixes, Support customer calls.',
    'VoIP or telecom support experience, SIP basics, Good troubleshooting process, Customer support confidence.',
    'Technical certification or hands-on telecom experience.',
    'Remote shifts, Weekly: 5 days.',
    'Home office support, Certification budget, Medical benefits.',
    'Career Recruit values careful technical support.',
    'active',
    '2026-11-14',
    '2026-11-14 23:59:59'
  ),
  (
    'Remote Telecom Project Coordinator',
    'remote-telecom-project-coordinator-signalpath',
    'SignalPath Networks',
    'Telecommunication',
    'Remote',
    'Contract',
    '$3,600 / Monthly',
    '2 Years',
    'Male or Female',
    'Diploma or degree',
    'Mid',
    '2',
    'Coordinate telecom rollout tasks, vendor updates, and client reporting for distributed infrastructure projects.',
    'Track project tasks, Schedule vendor updates, Prepare rollout reports, Maintain risk logs, Follow up on blockers.',
    'Project coordination experience, Telecom exposure, Strong spreadsheet skills, Clear written updates.',
    'Project management training or equivalent work experience.',
    'Remote contract schedule, Weekly: 5 days.',
    'Flexible remote work, Contract completion bonus, Tools allowance.',
    'Career Recruit supports organized project delivery.',
    'active',
    '2026-09-18',
    '2026-09-18 23:59:59'
  ),
  (
    'Remote Wireless Quality Tester',
    'remote-wireless-quality-tester-airlink',
    'AirLink Labs',
    'Telecommunication',
    'Remote',
    'Part-time',
    '$28 / Hourly',
    '2 Years',
    'Male or Female',
    'Technical background preferred',
    'Entry',
    '5',
    'Run remote quality checks on wireless service reports and document defects for network engineering teams.',
    'Review test reports, Validate issue details, Log defects, Share quality notes, Retest resolved issues.',
    'Quality testing experience, Basic wireless knowledge, Careful documentation, Reliable remote availability.',
    'Technical training or equivalent QA experience.',
    'Remote flexible hours, Weekly: 3-4 days.',
    'Flexible hours, Testing tools access, Paid onboarding.',
    'Career Recruit supports detail-focused QA work.',
    'active',
    '2026-08-21',
    '2026-08-21 23:59:59'
  ),
  (
    'Remote Payroll Assistant',
    'remote-payroll-assistant-paywise',
    'PayWise Services',
    'Accounting/Finance',
    'Remote',
    'Full-time',
    '$2,900 / Monthly',
    '2 Years',
    'Male or Female',
    'Accounting diploma preferred',
    'Entry',
    '3',
    'Assist payroll processing, employee record checks, and payment reconciliations for remote client teams.',
    'Review payroll inputs, Update records, Reconcile payment files, Flag exceptions, Prepare payroll summaries.',
    'Payroll or bookkeeping experience, Spreadsheet accuracy, Confidential data handling, Timely communication.',
    'Accounting diploma, finance coursework, or equivalent payroll experience.',
    'Remote schedule, Weekly: 5 days.',
    'Remote stipend, Paid leave, Finance training.',
    'Career Recruit supports accurate and confidential finance work.',
    'active',
    '2026-09-05',
    '2026-09-05 23:59:59'
  ),
  (
    'Remote Bookkeeping Specialist',
    'remote-bookkeeping-specialist-ledgerly',
    'Ledgerly',
    'Accounting/Finance',
    'Remote',
    'Full-time',
    '$3,500 / Monthly',
    '3 Years',
    'Male or Female',
    'Accounting or finance background',
    'Mid',
    '2',
    'Maintain client books, reconcile accounts, and prepare monthly finance packs for small business customers.',
    'Post transactions, Reconcile bank accounts, Prepare monthly summaries, Track missing documents, Support client questions.',
    'Bookkeeping experience, Accounting software familiarity, Strong reconciliation habits, Client service mindset.',
    'Accounting, finance, or equivalent bookkeeping experience.',
    'Remote schedule, Weekly: 5 days.',
    'Certification support, Remote tools, Paid leave.',
    'Career Recruit supports dependable finance operations.',
    'active',
    '2026-10-25',
    '2026-10-25 23:59:59'
  ),
  (
    'Remote Risk Reporting Analyst',
    'remote-risk-reporting-analyst-quantiva',
    'Quantiva Finance',
    'Accounting/Finance',
    'Remote',
    'Full-time',
    '$4,900 / Monthly',
    '4 Years',
    'Male or Female',
    'BSC Finance, Economics, or related',
    'Senior',
    '1',
    'Prepare risk reporting packs, analyze portfolio movement, and support governance reviews for finance leaders.',
    'Build risk reports, Validate source data, Investigate variances, Prepare review notes, Improve reporting controls.',
    'Risk reporting experience, Strong Excel or BI skills, Finance data understanding, Careful review process.',
    'Finance, economics, statistics, or equivalent analytical experience.',
    'Remote schedule, Weekly: 5 days.',
    'Health benefits, Annual bonus, Training budget, Remote allowance.',
    'Career Recruit supports responsible finance reporting.',
    'active',
    '2026-12-01',
    '2026-12-01 23:59:59'
  ),
  (
    'Remote UI Designer',
    'remote-ui-designer-pixelcraft',
    'PixelCraft Digital',
    'Design/Creative',
    'Remote',
    'Contract',
    '$45 / Hourly',
    '3 Years',
    'Male or Female',
    'Portfolio required',
    'Mid',
    '2',
    'Design responsive website screens, component states, and handoff notes for product and marketing teams.',
    'Create UI screens, Prepare component specs, Review responsive states, Support developer handoff, Maintain design files.',
    'Strong UI portfolio, Figma fluency, Responsive design understanding, Good visual hierarchy.',
    'Design degree preferred, strong portfolio accepted.',
    'Remote contract schedule, Weekly: 4-5 days.',
    'Flexible hours, Design tools support, Project bonus.',
    'Career Recruit encourages clean and usable design.',
    'active',
    '2026-11-26',
    '2026-11-26 23:59:59'
  ),
  (
    'Remote Brand Designer',
    'remote-brand-designer-lumaandco',
    'Luma & Co.',
    'Design/Creative',
    'Remote',
    'Full-time',
    '$4,200 / Monthly',
    '4 Years',
    'Male or Female',
    'Portfolio required',
    'Mid',
    '1',
    'Create campaign identities, social graphics, employer brand assets, and lightweight presentation systems.',
    'Design brand assets, Build campaign templates, Prepare presentation visuals, Organize asset libraries, Review final exports.',
    'Brand design portfolio, Typography and layout skill, Ability to follow briefs, Organized file delivery.',
    'Design education or equivalent portfolio experience.',
    'Remote schedule, Weekly: 5 days.',
    'Creative tools allowance, Healthcare support, Paid leave.',
    'Career Recruit supports thoughtful visual communication.',
    'active',
    '2026-09-27',
    '2026-09-27 23:59:59'
  ),
  (
    'Remote Motion Graphics Editor',
    'remote-motion-graphics-editor-frameflow',
    'FrameFlow Studio',
    'Design/Creative',
    'Remote',
    'Part-time',
    '$32 / Hourly',
    '3 Years',
    'Male or Female',
    'Portfolio required',
    'Mid',
    '2',
    'Edit short-form videos and motion graphics for job campaigns, social media, and employer branding packages.',
    'Edit video clips, Create motion titles, Export social formats, Organize project files, Apply brand guidelines.',
    'Motion portfolio, Video editing software experience, Good pacing and typography, Reliable delivery.',
    'Portfolio-based qualification accepted.',
    'Remote flexible hours, Weekly: 3-4 days.',
    'Flexible hours, Software support, Paid project reviews.',
    'Career Recruit supports creative remote collaboration.',
    'active',
    '2026-08-31',
    '2026-08-31 23:59:59'
  ),
  (
    'Remote Research Associate',
    'remote-research-associate-insightdeck',
    'InsightDeck Advisory',
    'Research/Consultancy',
    'Remote',
    'Full-time',
    '$3,800 / Monthly',
    '3 Years',
    'Male or Female',
    'BSC or research portfolio',
    'Mid',
    '3',
    'Support market research projects by gathering sources, cleaning survey data, and drafting client-ready findings.',
    'Collect research sources, Clean datasets, Draft insight summaries, Build simple charts, Support consultant requests.',
    'Research experience, Spreadsheet skill, Clear writing, Ability to verify sources.',
    'Research, business, economics, social science, or equivalent experience.',
    'Remote schedule, Weekly: 5 days.',
    'Research tools access, Paid leave, Learning budget.',
    'Career Recruit values careful evidence-based work.',
    'active',
    '2026-10-19',
    '2026-10-19 23:59:59'
  ),
  (
    'Remote Business Consultant',
    'remote-business-consultant-strategylane',
    'StrategyLane Partners',
    'Research/Consultancy',
    'Remote',
    'Contract',
    '$6,000 / Monthly',
    '6 Years',
    'Male or Female',
    'MBA preferred',
    'Senior',
    '1',
    'Lead remote client workshops, process reviews, and operating model recommendations for growing service companies.',
    'Run discovery sessions, Map business processes, Identify improvement areas, Prepare client decks, Present recommendations.',
    'Consulting experience, Strong facilitation, Business analysis skills, Executive communication.',
    'MBA preferred, equivalent consulting experience accepted.',
    'Remote contract schedule, Weekly: 5 days.',
    'Flexible remote work, Project bonus, Client travel reimbursement when needed.',
    'Career Recruit supports practical consulting outcomes.',
    'active',
    '2026-12-09',
    '2026-12-09 23:59:59'
  ),
  (
    'Remote Online Tutor',
    'remote-online-tutor-eduleap',
    'EduLeap',
    'Education/Training',
    'Remote',
    'Part-time',
    '$24 / Hourly',
    '2 Years',
    'Male or Female',
    'Teaching certificate preferred',
    'Entry',
    '7',
    'Teach live online lessons, review student assignments, and provide progress notes for learners across time zones.',
    'Deliver online classes, Review assignments, Share progress notes, Attend tutor briefings, Support learner questions.',
    'Teaching or tutoring experience, Clear speaking skills, Reliable internet, Patient learner support.',
    'Teaching certificate helpful, subject expertise accepted.',
    'Remote evening slots, Weekly: 3-5 days.',
    'Flexible schedule, Tutor resources, Paid onboarding.',
    'Career Recruit supports accessible online education.',
    'active',
    '2026-09-11',
    '2026-09-11 23:59:59'
  ),
  (
    'Remote Learning Content Developer',
    'remote-learning-content-developer-skillpath',
    'SkillPath Academy',
    'Education/Training',
    'Remote',
    'Full-time',
    '$4,000 / Monthly',
    '4 Years',
    'Male or Female',
    'Education or content background',
    'Mid',
    '2',
    'Develop online course outlines, lesson scripts, quizzes, and learner activities for professional training programs.',
    'Write lesson scripts, Build quiz banks, Review learning outcomes, Coordinate subject reviewers, Update course content.',
    'Instructional content experience, Strong writing, Curriculum planning, Attention to learner clarity.',
    'Education, instructional design, or equivalent content development experience.',
    'Remote schedule, Weekly: 5 days.',
    'Learning budget, Remote tools, Paid leave.',
    'Career Recruit supports practical skill development.',
    'active',
    '2026-11-03',
    '2026-11-03 23:59:59'
  ),
  (
    'Remote Data Entry Specialist',
    'remote-data-entry-specialist-datakeep',
    'DataKeep Services',
    'Data Entry/Operator',
    'Remote',
    'Full-time',
    '$2,400 / Monthly',
    '1 Year',
    'Male or Female',
    'High school diploma or equivalent',
    'Entry',
    '8',
    'Enter, clean, and verify applicant and employer records while maintaining accuracy and turnaround targets.',
    'Enter records, Validate source documents, Correct data errors, Track completion counts, Escalate missing information.',
    'Fast typing, Data accuracy, Basic spreadsheet skills, Reliable remote work setup.',
    'High school diploma, office training, or equivalent data work experience.',
    'Remote schedule, Weekly: 5 days.',
    'Remote work support, Paid training, Performance bonus.',
    'Career Recruit supports accurate back-office work.',
    'active',
    '2026-08-24',
    '2026-08-24 23:59:59'
  ),
  (
    'Remote Operations Clerk',
    'remote-operations-clerk-workqueue',
    'WorkQueue Admin',
    'Data Entry/Operator',
    'Remote',
    'Full-time',
    '$2,650 / Monthly',
    '2 Years',
    'Male or Female',
    'Office administration background',
    'Entry',
    '4',
    'Support remote operations by processing forms, updating trackers, and routing requests to the correct teams.',
    'Process forms, Update trackers, Route requests, Check document completeness, Prepare daily summaries.',
    'Administrative support experience, Spreadsheet comfort, Organized work habits, Clear written updates.',
    'Office administration training or equivalent work experience.',
    'Remote schedule, Weekly: 5 days.',
    'Paid training, Remote tools, Leave allowance.',
    'Career Recruit supports dependable operations teams.',
    'active',
    '2026-10-07',
    '2026-10-07 23:59:59'
  ),
  (
    'Remote Document Processor',
    'remote-document-processor-clearforms',
    'ClearForms',
    'Data Entry/Operator',
    'Remote',
    'Contract',
    '$22 / Hourly',
    '1 Year',
    'Male or Female',
    'Administrative experience preferred',
    'Entry',
    '5',
    'Review submitted forms, rename files, tag records, and prepare document batches for quality review.',
    'Review forms, Rename and tag files, Prepare batches, Flag unclear submissions, Meet daily processing targets.',
    'Document handling experience, Attention to detail, Basic computer skills, Consistent availability.',
    'Administrative training or equivalent document processing experience.',
    'Remote contract hours, Weekly: 4-5 days.',
    'Flexible shifts, Paid onboarding, Contract renewal option.',
    'Career Recruit supports organized document operations.',
    'active',
    '2026-09-16',
    '2026-09-16 23:59:59'
  ),
  (
    'Remote Customer Support Agent',
    'remote-customer-support-agent-helpdeskly',
    'HelpDeskly',
    'Security/Support Service',
    'Remote',
    'Full-time',
    '$3,000 / Monthly',
    '2 Years',
    'Male or Female',
    'Customer service background',
    'Entry',
    '6',
    'Respond to customer questions by chat and email, resolve common account issues, and escalate technical cases.',
    'Answer chat requests, Respond to support emails, Update ticket notes, Escalate technical issues, Share product feedback.',
    'Customer support experience, Strong written communication, Ticketing tool familiarity, Calm problem solving.',
    'Customer service training or equivalent support experience.',
    'Remote shifts, Weekly: 5 days.',
    'Shift allowance, Paid training, Remote equipment support.',
    'Career Recruit supports respectful customer service.',
    'active',
    '2026-11-22',
    '2026-11-22 23:59:59'
  ),
  (
    'Remote Wellness Coach',
    'remote-wellness-coach-fitwell',
    'FitWell Online',
    'Health & Fitness',
    'Remote',
    'Part-time',
    '$30 / Hourly',
    '3 Years',
    'Male or Female',
    'Fitness or wellness certification',
    'Mid',
    '2',
    'Guide virtual wellness sessions, track client progress, and support habit-building programs for remote professionals.',
    'Lead virtual sessions, Review client goals, Track wellness progress, Share habit plans, Support community check-ins.',
    'Wellness coaching experience, Certification, Good video presence, Supportive communication style.',
    'Fitness, nutrition, wellness, or coaching certification required.',
    'Remote flexible hours, Weekly: 3-4 days.',
    'Flexible schedule, Program resources, Performance bonus.',
    'Career Recruit supports healthy remote work.',
    'active',
    '2026-08-27',
    '2026-08-27 23:59:59'
  )
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  company_name = VALUES(company_name),
  category = VALUES(category),
  location = VALUES(location),
  job_type = VALUES(job_type),
  salary = VALUES(salary),
  experience = VALUES(experience),
  gender = VALUES(gender),
  qualification = VALUES(qualification),
  level = VALUES(level),
  vacancy = VALUES(vacancy),
  description = VALUES(description),
  responsibilities = VALUES(responsibilities),
  requirements = VALUES(requirements),
  education_requirements = VALUES(education_requirements),
  working_hours = VALUES(working_hours),
  benefits = VALUES(benefits),
  statement = VALUES(statement),
  status = VALUES(status),
  deadline = VALUES(deadline),
  expires_at = VALUES(expires_at);
