INSERT INTO jobs (
  title,
  slug,
  company_name,
  category,
  location,
  job_type,
  salary,
  experience,
  gender,
  qualification,
  level,
  vacancy,
  description,
  responsibilities,
  requirements,
  education_requirements,
  working_hours,
  benefits,
  statement,
  status,
  deadline,
  expires_at
)
VALUES
  (
    'Remote Operations Coordinator',
    'remote-operations-coordinator-flowops',
    'FlowOps Services',
    'Production/Operation',
    'Remote',
    'Full-time',
    '$3,400 / Monthly',
    '3 Years',
    'Male or Female',
    'Operations or administration background',
    'Mid',
    '2',
    'Coordinate remote production tasks, daily handoffs, vendor updates, and operating trackers for distributed service teams.',
    'Track daily operations, Coordinate handoffs, Update production boards, Follow up with vendors, Prepare status summaries.',
    'Operations coordination experience, Spreadsheet confidence, Clear written updates, Ability to manage multiple deadlines.',
    'Operations, business administration, logistics, or equivalent practical experience.',
    'Remote schedule, Weekly: 5 days.',
    'Remote tools allowance, Paid leave, Operations training, Performance bonus.',
    'Career Recruit supports organized operations teams.',
    'active',
    '2026-10-10',
    '2026-10-10 23:59:59'
  ),
  (
    'Production Planning Assistant',
    'production-planning-assistant-makewise',
    'MakeWise Manufacturing',
    'Production/Operation',
    'Chicago, USA',
    'Full-time',
    '$3,100 / Monthly',
    '2 Years',
    'Male or Female',
    'Diploma or degree preferred',
    'Entry',
    '3',
    'Support production schedules, material readiness checks, and daily reporting for a growing operations team.',
    'Update planning sheets, Check material readiness, Track production delays, Prepare daily reports, Support supervisor requests.',
    'Production or logistics support experience, Good spreadsheet skills, Careful reporting habits, Team communication.',
    'Operations, supply chain, business, or equivalent production support experience.',
    '8:00 AM - 5:00 PM, Weekly: 5 days.',
    'Medical support, Paid training, Transport allowance, Annual bonus.',
    'Career Recruit supports reliable production work.',
    'active',
    '2026-09-24',
    '2026-09-24 23:59:59'
  )
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  company_name = VALUES(company_name),
  category = VALUES(category),
  location = VALUES(location),
  job_type = VALUES(job_type),
  salary = VALUES(salary),
  experience = VALUES(experience),
  gender = VALUES(gender),
  qualification = VALUES(qualification),
  level = VALUES(level),
  vacancy = VALUES(vacancy),
  description = VALUES(description),
  responsibilities = VALUES(responsibilities),
  requirements = VALUES(requirements),
  education_requirements = VALUES(education_requirements),
  working_hours = VALUES(working_hours),
  benefits = VALUES(benefits),
  statement = VALUES(statement),
  status = VALUES(status),
  deadline = VALUES(deadline),
  expires_at = VALUES(expires_at);

UPDATE categories c
SET job_count = (
  SELECT COUNT(*)
  FROM jobs j
  WHERE j.category = c.name AND j.status = 'active'
);
