CREATE TABLE IF NOT EXISTS candidates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(80) NULL,
  title VARCHAR(160) NOT NULL,
  category VARCHAR(140) NULL,
  location VARCHAR(180) NULL,
  skills TEXT NULL,
  resume_url VARCHAR(255) NULL,
  photo_url VARCHAR(255) NULL,
  bio TEXT NULL,
  offered_salary VARCHAR(120) NULL,
  experience VARCHAR(80) NULL,
  language VARCHAR(160) NULL,
  age VARCHAR(80) NULL,
  gender VARCHAR(80) NULL,
  qualification VARCHAR(160) NULL,
  level VARCHAR(80) NULL,
  views INT NOT NULL DEFAULT 0,
  education TEXT NULL,
  work_experience TEXT NULL,
  professional_skills TEXT NULL,
  software_skills TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_candidates_title (title),
  INDEX idx_candidates_location (location)
);

INSERT INTO candidates (
  first_name,
  last_name,
  email,
  phone,
  title,
  category,
  location,
  skills,
  resume_url,
  photo_url,
  bio,
  offered_salary,
  experience,
  language,
  age,
  gender,
  qualification,
  level,
  views,
  education,
  work_experience,
  professional_skills,
  software_skills
)
VALUES
  (
    'Lauren',
    'Benitez',
    'lauren.benitez@example.com',
    '+1 212 555 0194',
    'Senior UI Designer',
    'Design/Creative',
    'New York, USA',
    'UI Design, UX Research, Figma, Design Systems, Prototyping',
    '#',
    'assets/img/team/1.jpg',
    'Senior product designer with a strong background in responsive web products, hiring platforms, and design systems. Lauren works closely with product and engineering teams to turn complex workflows into clear user experiences.',
    '$5,200 / Monthly',
    '6 Years',
    'English, Spanish',
    '29 Years',
    'Female',
    'BSC, Design Certificate',
    'Senior',
    8567,
    'Graphic Design // 2014 - 2018 // University of Michigan // Focused on visual communication, interaction design, and digital product foundations.|Human Centered Design // 2019 - 2020 // Franklin and Marshall College // Completed applied design research and prototyping coursework.',
    'UI Designer // 2018 - 2020 // Lambent Illumination Ltd. // Designed landing pages, dashboards, and mobile web flows for SaaS clients.|Senior UI Designer // 2020 - Present // Karibian IT Solution Ltd. // Leads interface design, design reviews, and product system documentation.',
    'Web application design, User interface design, Mobile application design, Landing page design, Interaction design, User experience, Branding and identity, Problem solving',
    'Figma, Adobe Photoshop, Adobe Illustrator, Adobe XD, Sketch, InVision Studio, Microsoft PowerPoint'
  ),
  (
    'Valentine',
    'Anders',
    'valentine.anders@example.com',
    '+1 415 555 0171',
    'Remote Product Designer',
    'Design/Creative',
    'Remote',
    'Product Design, UX Strategy, Wireframes, Figma, User Testing',
    '#',
    'assets/img/team/2.jpg',
    'Remote product designer experienced in fintech and recruitment tools. Valentine specializes in discovery, information architecture, and clean product handoff for distributed teams.',
    '$5,800 / Monthly',
    '7 Years',
    'English, French',
    '31 Years',
    'Male or Female',
    'BA, Product Design',
    'Senior',
    7342,
    'Product Design // 2013 - 2017 // California College of the Arts // Studied interaction design, prototyping, and product strategy.|UX Research Methods // 2018 - 2019 // Online Professional Program // Completed user interview, usability testing, and research synthesis projects.',
    'Product Designer // 2017 - 2021 // BrightPath Labs // Designed SaaS onboarding, reporting dashboards, and admin tools.|Remote Product Designer // 2021 - Present // Northstar Talent // Leads remote discovery and interface delivery for hiring products.',
    'Product strategy, Wireframing, User testing, Design systems, Responsive design, Stakeholder communication',
    'Figma, Miro, Maze, Notion, Adobe Illustrator, Google Analytics'
  ),
  (
    'Shakia',
    'Aguilera',
    'shakia.aguilera@example.com',
    '+1 512 555 0188',
    'Frontend Developer',
    'Engineer/Architects',
    'Austin, USA',
    'JavaScript, React, HTML5, CSS3, API Integration, Accessibility',
    '#',
    'assets/img/team/3.jpg',
    'Frontend developer focused on accessible, maintainable web applications. Shakia builds clean interfaces, connects APIs, and improves performance across product teams.',
    '$5,000 / Monthly',
    '5 Years',
    'English',
    '28 Years',
    'Female',
    'BSC Computer Science',
    'Mid',
    6821,
    'Computer Science // 2014 - 2018 // University of Texas // Studied software engineering, web development, and database systems.',
    'Frontend Engineer // 2018 - 2021 // Cogent Data // Built analytics dashboards and reusable UI components.|Frontend Developer // 2021 - Present // Greenline Commerce // Works on ecommerce flows, accessibility, and API integrations.',
    'JavaScript development, React components, Responsive UI, Accessibility, API integration, Performance tuning',
    'React, Git, Chrome DevTools, Figma, Jest, REST APIs'
  ),
  (
    'Assunta',
    'Manson',
    'assunta.manson@example.com',
    '+1 214 555 0133',
    'Mobile App Developer',
    'Engineer/Architects',
    'Dallas, USA',
    'React Native, JavaScript, Mobile UI, API Integration, App Store Delivery',
    '#',
    'assets/img/team/4.jpg',
    'Mobile app developer with experience building hiring, learning, and operations apps. Assunta is comfortable owning features from UI build through API integration and release support.',
    '$5,400 / Monthly',
    '6 Years',
    'English, Portuguese',
    '30 Years',
    'Female',
    'BSC Software Engineering',
    'Senior',
    6124,
    'Software Engineering // 2012 - 2016 // Dallas Technical University // Focused on mobile development, software architecture, and data structures.',
    'Mobile Developer // 2016 - 2019 // Sanguine Skincare Ltd. // Built customer mobile flows and loyalty features.|Senior Mobile Developer // 2019 - Present // FlowOps Services // Leads mobile feature delivery and release support.',
    'Mobile application design, React Native development, API integration, App release support, Debugging, Team collaboration',
    'React Native, Expo, Xcode, Android Studio, Firebase, Git'
  ),
  (
    'David',
    'Silva',
    'david.silva@example.com',
    '+1 305 555 0148',
    'Finance Operations Analyst',
    'Accounting/Finance',
    'Remote',
    'Finance Operations, Reconciliation, Reporting, Excel, Risk Checks',
    '#',
    'assets/img/team/5.jpg',
    'Finance operations analyst with strong reconciliation and reporting habits. David supports remote teams with accurate payment checks, variance reporting, and audit-ready documentation.',
    '$4,600 / Monthly',
    '4 Years',
    'English, Portuguese',
    '27 Years',
    'Male',
    'BSC Finance',
    'Mid',
    4930,
    'Finance // 2015 - 2019 // Florida International University // Studied accounting, reporting, corporate finance, and financial analysis.',
    'Finance Assistant // 2019 - 2021 // ClearLedger Group // Supported reconciliations and monthly reporting.|Finance Operations Analyst // 2021 - Present // Quantiva Finance // Owns payment exception tracking and risk reports.',
    'Financial reporting, Account reconciliation, Spreadsheet modeling, Audit support, Payment tracking',
    'Microsoft Excel, QuickBooks, Power BI, Google Sheets, SQL basics'
  ),
  (
    'Leona',
    'Spencer',
    'leona.spencer@example.com',
    '+1 646 555 0162',
    'Customer Support Specialist',
    'Security/Support Service',
    'Remote',
    'Customer Support, Ticketing, Live Chat, Knowledge Base, Escalation',
    '#',
    'assets/img/team/8.jpg',
    'Customer support specialist with a calm communication style and strong ticketing discipline. Leona helps customers solve account, billing, and product workflow issues.',
    '$3,200 / Monthly',
    '3 Years',
    'English',
    '26 Years',
    'Female',
    'BA Communications',
    'Mid',
    3844,
    'Communications // 2016 - 2020 // New York University // Focused on professional writing, customer communication, and digital media.',
    'Support Agent // 2020 - 2022 // HelpDeskly // Managed chat and email queues for SaaS customers.|Customer Support Specialist // 2022 - Present // HireGrid // Handles product questions, escalations, and documentation updates.',
    'Customer communication, Ticket management, Live chat support, Knowledge base writing, Escalation handling',
    'Zendesk, Intercom, Notion, Google Workspace, Slack'
  )
ON DUPLICATE KEY UPDATE
  first_name = VALUES(first_name),
  last_name = VALUES(last_name),
  phone = VALUES(phone),
  title = VALUES(title),
  category = VALUES(category),
  location = VALUES(location),
  skills = VALUES(skills),
  resume_url = VALUES(resume_url),
  photo_url = VALUES(photo_url),
  bio = VALUES(bio),
  offered_salary = VALUES(offered_salary),
  experience = VALUES(experience),
  language = VALUES(language),
  age = VALUES(age),
  gender = VALUES(gender),
  qualification = VALUES(qualification),
  level = VALUES(level),
  views = VALUES(views),
  education = VALUES(education),
  work_experience = VALUES(work_experience),
  professional_skills = VALUES(professional_skills),
  software_skills = VALUES(software_skills);
