CREATE TABLE IF NOT EXISTS blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(240) NOT NULL,
  excerpt TEXT NOT NULL,
  content MEDIUMTEXT NOT NULL,
  author VARCHAR(120) NOT NULL DEFAULT 'Career Recruit Editorial',
  category VARCHAR(120) NOT NULL DEFAULT 'Hiring Advice',
  tags VARCHAR(255) NULL,
  image_url VARCHAR(255) NULL,
  hero_image_url VARCHAR(255) NULL,
  read_time VARCHAR(40) NOT NULL DEFAULT '6 min read',
  status VARCHAR(30) NOT NULL DEFAULT 'published',
  published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_blogs_slug (slug),
  KEY idx_blogs_status (status),
  KEY idx_blogs_category (category),
  KEY idx_blogs_published (published_at)
);

CREATE TABLE IF NOT EXISTS blog_comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  blog_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  role_location VARCHAR(180) NULL,
  message TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'approved',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_blog_comments_blog (blog_id),
  KEY idx_blog_comments_status (status),
  CONSTRAINT fk_blog_comments_blog FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE
);

ALTER TABLE blog_comments DROP INDEX uniq_blog_comment_email;

INSERT INTO blogs (title, slug, excerpt, content, author, category, tags, image_url, hero_image_url, read_time, status, published_at) VALUES
('How to Write a Job Post That Attracts Qualified Candidates', 'how-to-write-a-job-post-that-attracts-qualified-candidates', 'A practical guide to writing clear job posts that help candidates self-select and improve the quality of applications.', 'Strong job posts do more than announce an opening. They explain the work, the outcomes expected in the first months, the skills that matter, and the hiring process. Candidates respond better when salary, location, work type, and required experience are easy to scan. Use direct language, avoid internal abbreviations, and separate must-have requirements from nice-to-have skills. A clear post reduces unqualified applications and helps serious candidates prepare stronger responses.', 'Career Recruit Editorial', 'Hiring Advice', 'job posts,hiring,candidates', 'assets/img/blog/1.jpg', 'assets/img/blog/details1.jpg', '7 min read', 'published', '2026-07-21 09:00:00'),
('What Remote Candidates Look for Before They Apply', 'what-remote-candidates-look-for-before-they-apply', 'Remote applicants compare clarity, trust, flexibility, and communication before submitting a resume.', 'Remote roles attract wide interest, but strong candidates still look for signals of quality. They want to know the expected time zone overlap, whether the role is fully remote or hybrid, how communication works, and whether compensation is realistic for the market. Employers should state tools, meeting expectations, reporting lines, and onboarding support. These details reduce confusion and make your listing more competitive.', 'Maya Bennett', 'Remote Work', 'remote jobs,applications,onboarding', 'assets/img/blog/2.jpg', 'assets/img/blog/details2.jpg', '6 min read', 'published', '2026-07-20 10:30:00'),
('Employer Verification Builds Trust in Job Marketplaces', 'employer-verification-builds-trust-in-job-marketplaces', 'Why verifying employers protects candidates and makes a job listing platform stronger.', 'Candidate trust is one of the most important assets of a job platform. Employer verification reduces fake listings, payment disputes, duplicate accounts, and unclear company identities. A simple admin review process helps keep the marketplace clean while giving legitimate employers a professional path to publish roles. Verification should be clear at registration, including any fee, payment wallet, and approval timeline.', 'Daniel Cross', 'Platform Trust', 'verification,employers,trust', 'assets/img/blog/3.jpg', 'assets/img/blog/details1.jpg', '5 min read', 'published', '2026-07-19 08:45:00'),
('The Candidate Profile Details Recruiters Actually Read', 'the-candidate-profile-details-recruiters-actually-read', 'Recruiters scan profiles quickly, so the right structure helps candidates stand out.', 'A strong candidate profile should quickly show role title, location preference, core skills, experience level, salary expectation, and recent work history. Recruiters often read the headline, summary, skills, and latest role before moving deeper. Candidates should use measurable outcomes where possible and keep long paragraphs under control. Good profile structure helps recruiters decide who to contact first.', 'Career Recruit Editorial', 'Candidate Tips', 'profiles,resumes,recruiters', 'assets/img/blog/4.jpg', 'assets/img/blog/details2.jpg', '6 min read', 'published', '2026-07-18 11:15:00'),
('How Job Categories Improve Search and Applications', 'how-job-categories-improve-search-and-applications', 'Well-planned categories make job discovery easier for candidates and reporting easier for admins.', 'Categories are more than navigation labels. They help candidates filter roles, help employers position openings, and help admins understand marketplace demand. Keep category names familiar, avoid overlapping labels, and review counts regularly. When categories match how candidates actually search, the job board feels easier to use and applications become more relevant.', 'Renee Carter', 'Job Search', 'categories,search,job board', 'assets/img/blog/5.jpg', 'assets/img/blog/details1.jpg', '5 min read', 'published', '2026-07-17 12:00:00'),
('A Better Registration Flow for Employers', 'a-better-registration-flow-for-employers', 'Employer registration works best when payment, verification, and approval expectations are clear upfront.', 'Employers want to know what happens after registration. Show the fee before the form is submitted, provide the wallet name and wallet address at the right moment, and explain that admin verification is required before publishing. A good flow collects the needed details, prevents accidental payment mistakes, and gives admins enough information to approve serious employers quickly.', 'Nora Fields', 'Employer Onboarding', 'registration,payments,verification', 'assets/img/blog/6.jpg', 'assets/img/blog/details2.jpg', '6 min read', 'published', '2026-07-16 09:40:00'),
('What Makes a Job Details Page Useful', 'what-makes-a-job-details-page-useful', 'The details page should answer the questions candidates ask before applying.', 'A useful job details page includes role summary, responsibilities, requirements, benefits, working hours, deadline, salary, and company information. Candidates should not need to guess whether they qualify. The best pages are direct, structured, and easy to scan on mobile. Clear details also reduce back-and-forth questions for employers.', 'Samuel Price', 'Job Search', 'job details,applications,candidate experience', 'assets/img/blog/7.jpg', 'assets/img/blog/details1.jpg', '7 min read', 'published', '2026-07-15 14:10:00'),
('Why Admin Dashboards Need Clear Content Management', 'why-admin-dashboards-need-clear-content-management', 'A good admin area lets teams keep jobs, categories, candidates, payments, and testimonials current.', 'A job listing site changes constantly. New roles are added, candidates update profiles, employers need verification, and public content must stay accurate. Admin dashboards should separate high-level overview from management pages. This makes repeated work faster and reduces mistakes. Cards, sidebars, and focused forms help admins update the site without touching code.', 'Career Recruit Editorial', 'Admin Operations', 'admin,content management,dashboard', 'assets/img/blog/8.jpg', 'assets/img/blog/details2.jpg', '6 min read', 'published', '2026-07-14 13:25:00'),
('How to Screen Remote Operations Roles', 'how-to-screen-remote-operations-roles', 'Remote operations hiring needs practical checks around communication, ownership, and process discipline.', 'Remote operations roles often require calm execution, written communication, and strong follow-through. Employers should screen for examples of process improvement, reporting habits, tool experience, and response standards. Candidates should be asked how they manage handoffs, escalations, and time zone differences. These signals matter more than generic interview answers.', 'Amara Okoye', 'Remote Work', 'operations,remote hiring,screening', 'assets/img/blog/9.jpg', 'assets/img/blog/details1.jpg', '8 min read', 'published', '2026-07-13 10:00:00'),
('Salary Transparency Helps Both Employers and Candidates', 'salary-transparency-helps-both-employers-and-candidates', 'Clear salary information saves time and improves trust in the hiring process.', 'Salary transparency helps candidates decide whether a role fits their needs before applying. It also helps employers receive applications from people aligned with the budget. If an exact number is not possible, publish a realistic range and explain what affects placement inside that range. Vague salary language often creates wasted conversations.', 'Liam Stone', 'Hiring Advice', 'salary,trust,job posts', 'assets/img/blog/10.jpg', 'assets/img/blog/details2.jpg', '5 min read', 'published', '2026-07-12 09:10:00'),
('How Candidates Can Prepare for Recruiter Shortlists', 'how-candidates-can-prepare-for-recruiter-shortlists', 'A complete profile and focused resume improve the chance of being shortlisted.', 'Shortlists are usually built from a quick comparison of role fit, skill match, recent experience, and availability. Candidates can improve their odds by keeping contact details current, using a clear title, adding measurable achievements, and matching skills to the role category. A strong profile makes the recruiter confident enough to move forward.', 'Career Recruit Editorial', 'Candidate Tips', 'shortlist,resume,profile', 'assets/img/blog/11.jpg', 'assets/img/blog/details1.jpg', '6 min read', 'published', '2026-07-11 16:20:00'),
('Building Trust With Testimonials on a Job Platform', 'building-trust-with-testimonials-on-a-job-platform', 'Client testimonials give new employers and candidates evidence that the platform works.', 'Testimonials should be specific. Instead of generic praise, strong testimonials mention faster hiring, better candidate quality, clearer registration, or easier admin management. Keep the client name, designation, message, rating, and image current. Fresh testimonials help a job platform feel active and credible.', 'Priya Adams', 'Platform Trust', 'testimonials,credibility,clients', 'assets/img/blog/12.jpg', 'assets/img/blog/details2.jpg', '5 min read', 'published', '2026-07-10 11:00:00'),
('The Best Way to Organize Hiring Content on a Homepage', 'the-best-way-to-organize-hiring-content-on-a-homepage', 'Homepages work better when real listings, categories, candidates, and client proof are pulled from the database.', 'A job marketplace homepage should show live information. Real job listings, active categories, candidate previews, and client testimonials are more useful than static demo blocks. When homepage content comes from the database, admins can keep the site fresh without editing templates. This also makes search and discovery feel consistent across pages.', 'Career Recruit Editorial', 'Admin Operations', 'homepage,content,database', 'assets/img/blog/1.jpg', 'assets/img/blog/details1.jpg', '6 min read', 'published', '2026-07-09 15:45:00'),
('Why Comment Sections Matter on Career Blogs', 'why-comment-sections-matter-on-career-blogs', 'Comments let candidates and employers ask follow-up questions and share practical experience.', 'A useful career blog is not only an article archive. Comments let readers ask questions, share hiring experiences, and clarify advice. Keep the form simple with name, email, role or location, and message. Moderation can be added later, but the first goal is to make conversation possible and easy.', 'Maya Bennett', 'Platform Trust', 'comments,community,career blog', 'assets/img/blog/2.jpg', 'assets/img/blog/details2.jpg', '4 min read', 'published', '2026-07-08 12:35:00'),
('How to Review Candidate Skills Without Overcomplicating Hiring', 'how-to-review-candidate-skills-without-overcomplicating-hiring', 'Simple skill review beats long unclear hiring steps for many roles.', 'Employers should connect skills directly to job outcomes. For example, a customer support role may require written communication, CRM experience, escalation handling, and reporting discipline. A developer role may require specific frameworks and code review habits. Skill checks should be practical and tied to the work, not just a long list of buzzwords.', 'Daniel Cross', 'Hiring Advice', 'skills,screening,hiring process', 'assets/img/blog/3.jpg', 'assets/img/blog/details1.jpg', '7 min read', 'published', '2026-07-07 09:30:00'),
('What Employers Should Include Before Publishing a Role', 'what-employers-should-include-before-publishing-a-role', 'A checklist for employers preparing a job listing for better candidate response.', 'Before publishing, employers should confirm the title, category, location, work type, salary, responsibilities, requirements, benefits, deadline, and application instructions. The listing should be clear enough for a candidate to decide quickly. Admin review can catch missing fields, vague content, and duplicated postings before they go live.', 'Renee Carter', 'Employer Onboarding', 'employers,publishing,jobs', 'assets/img/blog/4.jpg', 'assets/img/blog/details2.jpg', '6 min read', 'published', '2026-07-06 13:50:00'),
('How Career Blogs Support Job Seekers Between Applications', 'how-career-blogs-support-job-seekers-between-applications', 'Helpful articles keep candidates engaged while they search, apply, and prepare.', 'Candidates need more than listings. They need advice on profiles, interviews, salary expectations, remote work, and how recruiters evaluate applications. A practical blog gives job seekers reasons to return even when they are not applying that day. This strengthens the platform and improves the candidate experience.', 'Nora Fields', 'Candidate Tips', 'job seekers,career advice,applications', 'assets/img/blog/5.jpg', 'assets/img/blog/details1.jpg', '5 min read', 'published', '2026-07-05 08:25:00'),
('Measuring Job Board Quality Beyond Traffic', 'measuring-job-board-quality-beyond-traffic', 'Traffic matters, but applications, employer quality, and successful matches matter more.', 'A job board can attract visitors and still underperform if listings are poor or candidate fit is weak. Better metrics include completed applications, verified employers, active categories, shortlist rates, and time to fill. Admin dashboards should help teams see where quality is improving and where content needs work.', 'Samuel Price', 'Admin Operations', 'metrics,quality,job board', 'assets/img/blog/6.jpg', 'assets/img/blog/details2.jpg', '7 min read', 'published', '2026-07-04 10:05:00'),
('How to Make Mobile Job Search Easier', 'how-to-make-mobile-job-search-easier', 'Most candidates browse on phones, so search, cards, and details must be easy to scan.', 'Mobile job search depends on fast scanning. Keep filters simple, buttons large enough, titles readable, and key details visible before the candidate opens the full page. Search should preserve query, category, and location. Details pages should avoid heavy clutter and keep apply actions clear.', 'Amara Okoye', 'Job Search', 'mobile,search,candidate experience', 'assets/img/blog/7.jpg', 'assets/img/blog/details1.jpg', '5 min read', 'published', '2026-07-03 14:45:00'),
('A Practical Hiring Workflow for Small Teams', 'a-practical-hiring-workflow-for-small-teams', 'Small teams need a repeatable process that does not slow down daily work.', 'A simple hiring workflow starts with a clear role brief, a complete job post, an application review rhythm, shortlist criteria, interview notes, and final approval. Small teams should keep the process visible and avoid adding unnecessary steps. The goal is to move quickly while still treating candidates fairly.', 'Career Recruit Editorial', 'Hiring Advice', 'workflow,small teams,hiring', 'assets/img/blog/8.jpg', 'assets/img/blog/details2.jpg', '6 min read', 'published', '2026-07-02 09:00:00')
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  excerpt = VALUES(excerpt),
  content = VALUES(content),
  author = VALUES(author),
  category = VALUES(category),
  tags = VALUES(tags),
  image_url = VALUES(image_url),
  hero_image_url = VALUES(hero_image_url),
  read_time = VALUES(read_time),
  status = VALUES(status),
  published_at = VALUES(published_at);

DELETE bc FROM blog_comments bc JOIN blogs b ON bc.blog_id = b.id WHERE b.slug IN ('how-to-write-a-job-post-that-attracts-qualified-candidates', 'what-remote-candidates-look-for-before-they-apply', 'employer-verification-builds-trust-in-job-marketplaces') AND bc.email IN ('tasha@example.com', 'kevin@example.com', 'amina@example.com');

INSERT INTO blog_comments (blog_id, name, email, role_location, message, status)
SELECT id, 'Tasha Williams', 'tasha@example.com', 'Talent Coordinator, Austin', 'This is useful. Clear salary and remote expectations always reduce wasted interviews for our team.', 'approved'
FROM blogs WHERE slug = 'how-to-write-a-job-post-that-attracts-qualified-candidates';

INSERT INTO blog_comments (blog_id, name, email, role_location, message, status)
SELECT id, 'Kevin Moore', 'kevin@example.com', 'Frontend Candidate, Remote', 'The advice about time zone overlap is important. I always check that before applying to remote jobs.', 'approved'
FROM blogs WHERE slug = 'what-remote-candidates-look-for-before-they-apply';

INSERT INTO blog_comments (blog_id, name, email, role_location, message, status)
SELECT id, 'Amina Cole', 'amina@example.com', 'HR Manager, Lagos', 'Employer verification makes the marketplace feel safer for both sides. Good direction for the platform.', 'approved'
FROM blogs WHERE slug = 'employer-verification-builds-trust-in-job-marketplaces';
